// OMDb has no "discover a random popular movie" endpoint (unlike TMDB's
// /discover), so we keep our own pool of well-known titles to pick from at
// random, then fetch the actual data for the pick from OMDb by title+year.
export const MOVIE_POOL = [
  { title: "The Shawshank Redemption", year: 1994 },
  { title: "The Godfather", year: 1972 },
  { title: "The Dark Knight", year: 2008 },
  { title: "Pulp Fiction", year: 1994 },
  { title: "Forrest Gump", year: 1994 },
  { title: "Inception", year: 2010 },
  { title: "Fight Club", year: 1999 },
  { title: "The Matrix", year: 1999 },
  { title: "Goodfellas", year: 1990 },
  { title: "The Silence of the Lambs", year: 1991 },
  { title: "Se7en", year: 1995 },
  { title: "The Green Mile", year: 1999 },
  { title: "Gladiator", year: 2000 },
  { title: "The Departed", year: 2006 },
  { title: "The Prestige", year: 2006 },
  { title: "Interstellar", year: 2014 },
  { title: "Whiplash", year: 2014 },
  { title: "Parasite", year: 2019 },
  { title: "Joker", year: 2019 },
  { title: "The Wolf of Wall Street", year: 2013 },
  { title: "Django Unchained", year: 2012 },
  { title: "Inglourious Basterds", year: 2009 },
  { title: "Saving Private Ryan", year: 1998 },
  { title: "Schindler's List", year: 1993 },
  { title: "Jurassic Park", year: 1993 },
  { title: "Titanic", year: 1997 },
  { title: "Avatar", year: 2009 },
  { title: "The Avengers", year: 2012 },
  { title: "Avengers: Endgame", year: 2019 },
  { title: "Iron Man", year: 2008 },
  { title: "Black Panther", year: 2018 },
  { title: "Spider-Man: Into the Spider-Verse", year: 2018 },
  { title: "Guardians of the Galaxy", year: 2014 },
  { title: "Guardians of the Galaxy Vol. 2", year: 2017 },
  { title: "Deadpool", year: 2016 },
  { title: "Logan", year: 2017 },
  { title: "Wonder Woman", year: 2017 },
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
  { title: "The Lord of the Rings: The Two Towers", year: 2002 },
  { title: "The Lord of the Rings: The Return of the King", year: 2003 },
  { title: "Star Wars", year: 1977 },
  { title: "The Empire Strikes Back", year: 1980 },
  { title: "Star Wars: The Force Awakens", year: 2015 },
  { title: "Back to the Future", year: 1985 },
  { title: "Raiders of the Lost Ark", year: 1981 },
  { title: "E.T. the Extra-Terrestrial", year: 1982 },
  { title: "Jaws", year: 1975 },
  { title: "Alien", year: 1979 },
  { title: "Aliens", year: 1986 },
  { title: "Terminator 2: Judgment Day", year: 1991 },
  { title: "The Terminator", year: 1984 },
  { title: "Die Hard", year: 1988 },
  { title: "Mad Max: Fury Road", year: 2015 },
  { title: "Gravity", year: 2013 },
  { title: "The Martian", year: 2015 },
  { title: "Arrival", year: 2016 },
  { title: "Blade Runner", year: 1982 },
  { title: "Blade Runner 2049", year: 2017 },
  { title: "No Country for Old Men", year: 2007 },
  { title: "There Will Be Blood", year: 2007 },
  { title: "American Beauty", year: 1999 },
  { title: "American History X", year: 1998 },
  { title: "Requiem for a Dream", year: 2000 },
  { title: "Memento", year: 2000 },
  { title: "Shutter Island", year: 2010 },
  { title: "Get Out", year: 2017 },
  { title: "Us", year: 2019 },
  { title: "A Quiet Place", year: 2018 },
  { title: "Hereditary", year: 2018 },
  { title: "The Shining", year: 1980 },
  { title: "Psycho", year: 1960 },
  { title: "Rear Window", year: 1954 },
  { title: "Vertigo", year: 1958 },
  { title: "North by Northwest", year: 1959 },
  { title: "Casablanca", year: 1942 },
  { title: "Citizen Kane", year: 1941 },
  { title: "12 Angry Men", year: 1957 },
  { title: "One Flew Over the Cuckoo's Nest", year: 1975 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "Full Metal Jacket", year: 1987 },
  { title: "Platoon", year: 1986 },
  { title: "Braveheart", year: 1995 },
  { title: "Gladiator II", year: 2024 },
  { title: "Oppenheimer", year: 2023 },
  { title: "Barbie", year: 2023 },
  { title: "Dune", year: 2021 },
  { title: "Dune: Part Two", year: 2024 },
  { title: "Everything Everywhere All at Once", year: 2022 },
  { title: "The Grand Budapest Hotel", year: 2014 },
  { title: "Moonrise Kingdom", year: 2012 },
  { title: "La La Land", year: 2016 },
  { title: "Whiplash", year: 2014 },
  { title: "Little Miss Sunshine", year: 2006 },
  { title: "Lost in Translation", year: 2003 },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004 },
  { title: "The Truman Show", year: 1998 },
  { title: "Big Fish", year: 2003 },
  { title: "Edward Scissorhands", year: 1990 },
  { title: "Beetlejuice", year: 1988 },
  { title: "The Nightmare Before Christmas", year: 1993 },
  { title: "Coraline", year: 2009 },
  { title: "Spirited Away", year: 2001 },
  { title: "My Neighbor Totoro", year: 1988 },
  { title: "Toy Story", year: 1995 },
  { title: "Toy Story 3", year: 2010 },
  { title: "Finding Nemo", year: 2003 },
  { title: "Up", year: 2009 },
  { title: "WALL-E", year: 2008 },
  { title: "Inside Out", year: 2015 },
  { title: "Coco", year: 2017 },
  { title: "Ratatouille", year: 2007 },
  { title: "The Incredibles", year: 2004 },
  { title: "Shrek", year: 2001 },
  { title: "How to Train Your Dragon", year: 2010 },
  { title: "Zootopia", year: 2016 },
  { title: "Frozen", year: 2013 },
  { title: "Moana", year: 2016 },
  { title: "The Lion King", year: 1994 },
  { title: "Aladdin", year: 1992 },
  { title: "Beauty and the Beast", year: 1991 },
  { title: "Harry Potter and the Sorcerer's Stone", year: 2001 },
  { title: "Harry Potter and the Prisoner of Azkaban", year: 2004 },
  { title: "Harry Potter and the Deathly Hallows: Part 2", year: 2011 },
  { title: "The Hunger Games", year: 2012 },
  { title: "La Haine", year: 1995 },
  { title: "City of God", year: 2002 },
  { title: "Amelie", year: 2001 },
  { title: "Pan's Labyrinth", year: 2006 },
  { title: "The Shape of Water", year: 2017 },
  { title: "Roma", year: 2018 },
  { title: "Moonlight", year: 2016 },
  { title: "12 Years a Slave", year: 2013 },
  { title: "Spotlight", year: 2015 },
  { title: "The Social Network", year: 2010 },
  { title: "Zodiac", year: 2007 },
  { title: "Gone Girl", year: 2014 },
  { title: "Knives Out", year: 2019 },
  { title: "Glass Onion: A Knives Out Mystery", year: 2022 },
  { title: "The Grand Illusion", year: 1937 },
  { title: "Léon: The Professional", year: 1994 },
  { title: "Heat", year: 1995 },
  { title: "Collateral", year: 2004 },
  { title: "Drive", year: 2011 },
  { title: "Baby Driver", year: 2017 },
  { title: "John Wick", year: 2014 },
  { title: "Mission: Impossible - Fallout", year: 2018 },
  { title: "Top Gun: Maverick", year: 2022 },
  { title: "Rocky", year: 1976 },
  { title: "Creed", year: 2015 },
  { title: "The Karate Kid", year: 1984 },
  { title: "Rain Man", year: 1988 },
  { title: "Good Will Hunting", year: 1997 },
  { title: "Dead Poets Society", year: 1989 },
  { title: "The Pursuit of Happyness", year: 2006 },
  { title: "A Beautiful Mind", year: 2001 },
  { title: "The Imitation Game", year: 2014 },
  { title: "Hidden Figures", year: 2016 },
  { title: "Ford v Ferrari", year: 2019 },
];
